server.port=8081
spring.application.name=ev
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=ThisIsMyVeryLongSecretKeyForSecureNotesApplication2026!
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
file.upload-dir=uploads
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}
# Maximum file size
spring.servlet.multipart.max-file-size=10MB

# Maximum request size
spring.servlet.multipart.max-request-size=10MB
# Gmail SMTP

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:465}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

























































































































































































































































































